import { Archive, ArchiveX, Check, ChevronLeft, CirclePlus, Copy, Download, Pencil, Pin, Search, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Button } from '../ui/button'
import { Input } from '../ui/input'
import { Dialog } from '../ui/dialog'
import { cn } from '../../lib/cn'
import { filterSessions, groupSessionsByDate, type SessionSummary } from '../../lib/chat-contract'
import { projectSessions } from '../../lib/conversation-runtime'
import { sessionExportUrl } from '../../lib/api-client'
import { DropdownMenu } from '../ui/dropdown-menu'

type Props = { sessions: SessionSummary[]; activeSessionId: string; onSelectSession: (id: string) => void; onSearch?: (query: string) => Promise<unknown>; onRename: (id: string, title: string) => Promise<void>; onPin: (id: string, pinned: boolean) => void; onArchive: (id: string, archived: boolean) => void; onDelete: (id: string) => Promise<void>; onDuplicate?: (id: string) => Promise<void>; onNewChat: () => void; loading: boolean; error?: string; onToggle: () => void }
type SourceFilter = 'all' | 'webui' | 'cli'

function field(session: SessionSummary, ...keys: string[]) { for (const key of keys) { const value = session[key]; if (typeof value === 'string' && value.trim()) return value.trim() } return '' }
function sourceOf(session: SessionSummary): SourceFilter { const source = field(session, 'source', 'session_source', 'origin', 'session_type').toLocaleLowerCase(); return source.includes('cli') || source.includes('cron') ? 'cli' : 'webui' }
function channelOf(session: SessionSummary) { return field(session, 'channel', 'channel_name', 'external_channel', 'transport') }

export function SessionRail({ sessions, activeSessionId, onSelectSession, onSearch, onRename, onPin, onArchive, onDelete, onDuplicate, onNewChat, loading, error, onToggle }: Props) {
  const [query, setQuery] = useState(''); const [sourceFilter, setSourceFilter] = useState<SourceFilter>('all'); const [projectFilter, setProjectFilter] = useState('all'); const [selected, setSelected] = useState<string[]>([]); const [batchMode, setBatchMode] = useState(false); const [renameTarget, setRenameTarget] = useState<SessionSummary | null>(null); const [deleteTarget, setDeleteTarget] = useState<SessionSummary | null>(null); const [renameValue, setRenameValue] = useState('')
  const projects = useMemo(() => Array.from(new Set(sessions.map(item => item.project || item.project_id).filter((item): item is string => Boolean(item)))).sort(), [sessions])
  const visible = filterSessions(sessions, query).filter(item => (sourceFilter === 'all' || sourceOf(item) === sourceFilter) && (projectFilter === 'all' || (item.project || item.project_id) === projectFilter))
  const groups = groupSessionsByDate(visible)
  const activeProjection = useMemo(() => projectSessions(sessions).find(item => item.session_id === activeSessionId), [sessions, activeSessionId])
  useEffect(() => { if (!onSearch) return; const timer = window.setTimeout(() => { void onSearch(query) }, 250); return () => window.clearTimeout(timer) }, [onSearch, query])
  const toggleSelected = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const clearBatch = () => { setSelected([]); setBatchMode(false) }

  return <>
    <aside className="hidden w-[280px] shrink-0 flex-col border-r bg-card/25 p-3 lg:flex" aria-label="Recent sessions">
      <div className="flex items-center gap-2 border-b pb-3"><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-foreground">Chat</p><p className="mt-0.5 text-[11px] text-muted-foreground">Recent sessions</p></div><Button type="button" size="sm" className="h-11 shrink-0 px-2 text-xs" onClick={onNewChat}><CirclePlus size={14} />New</Button><Button variant="ghost" size="icon" className="size-11 shrink-0" onClick={onToggle} aria-label="Collapse session sidebar"><ChevronLeft size={16} /></Button></div>
      <div className="relative mt-3"><Search size={14} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input id="session-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search titles and content" className="h-9 bg-background/50 pl-9 text-xs" aria-label="Search sessions" /></div>
      <div className="mt-2 flex gap-1" role="group" aria-label="Session source filter">{(['all', 'webui', 'cli'] as const).map(filter => <Button key={filter} size="sm" variant={sourceFilter === filter ? 'default' : 'outline'} className="min-h-11 flex-1 px-1 text-[10px]" onClick={() => setSourceFilter(filter)}>{filter === 'all' ? 'All' : filter === 'webui' ? 'WebUI' : 'CLI'}</Button>)}</div>
      <div className="mt-2 flex gap-1 overflow-x-auto pb-1" role="group" aria-label="Session project filter"><Button size="sm" variant={projectFilter === 'all' ? 'default' : 'outline'} className="min-h-11 shrink-0 px-2 text-[10px]" onClick={() => setProjectFilter('all')}>All projects</Button>{projects.map(project => <Button key={project} size="sm" variant={projectFilter === project ? 'default' : 'outline'} className="min-h-11 max-w-28 shrink-0 truncate px-2 text-[10px]" onClick={() => setProjectFilter(project)}>{project}</Button>)}</div>
      {activeProjection?.external && <section className="mt-2 rounded-lg border border-primary/25 bg-primary/5 p-2.5" aria-label="External session handoff"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary" aria-hidden="true" /><p className="min-w-0 flex-1 truncate text-xs font-medium">{channelOf(activeProjection) || activeProjection.source} session</p><span className="text-[10px] uppercase tracking-wide text-muted-foreground">External</span></div><p className="mt-1 truncate text-[11px] text-muted-foreground">{field(activeProjection, 'identity', 'sender', 'user_name') || 'Identity not provided'} · {field(activeProjection, 'routing', 'route', 'model') || 'Routing not provided'}</p><Button type="button" size="sm" variant="outline" className="mt-2 h-8 w-full text-[11px]" disabled title="External handoff requires an upstream channel contract">Handoff unavailable</Button></section>}
      <div className="mt-1 flex min-h-11 items-center justify-end gap-1">{batchMode && selected.length > 0 && <><span className="mr-auto text-[10px] text-muted-foreground">{selected.length} selected</span><Button size="sm" variant="outline" className="min-h-11 px-2 text-[10px]" onClick={async () => { await Promise.all(selected.map(id => onArchive(id, true))); clearBatch() }}>Archive</Button><Button size="sm" variant="outline" className="min-h-11 px-2 text-[10px] text-destructive" onClick={async () => { await Promise.all(selected.map(onDelete)); clearBatch() }}>Delete</Button></>}<Button size="sm" variant={batchMode ? 'default' : 'ghost'} className="min-h-11 px-2 text-[10px]" onClick={() => { setBatchMode(value => !value); setSelected([]) }} aria-pressed={batchMode}>{batchMode ? 'Done' : 'Select'}</Button></div>
      <div className="thin-scrollbar mt-1 min-h-0 flex-1 space-y-1 overflow-y-auto">
        {loading && <p className="px-3 py-2 text-xs text-muted-foreground" role="status">Loading session history...</p>}{error && <p className="px-3 py-2 text-xs text-destructive" role="alert">{error}</p>}{!loading && !error && !sessions.length && <p className="px-3 py-2 text-xs text-muted-foreground">No saved sessions yet.</p>}
        {!loading && !error && groups.map(group => <div key={group.label} className="pt-2"><p className="px-3 pb-1 text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground">{group.label}</p>{group.sessions.map(item => { const channel = channelOf(item); const isSelected = selected.includes(item.session_id); return <div key={item.session_id} className={cn('group relative flex min-h-11 items-center rounded-lg px-2 py-1 hover:bg-accent/70', item.session_id === activeSessionId && 'bg-accent/60', isSelected && 'ring-1 ring-primary/60')}>
          {batchMode && <Button type="button" variant="ghost" size="icon" className="size-11" onClick={() => toggleSelected(item.session_id)} aria-label={`${isSelected ? 'Deselect' : 'Select'} ${item.title || 'session'}`}>{isSelected ? <Check size={15} /> : <span className="size-3 rounded-sm border" />}</Button>}
          <Button type="button" variant="ghost" size="sm" onClick={() => onSelectSession(item.session_id)} aria-current={item.session_id === activeSessionId ? 'page' : undefined} className="h-auto min-h-11 min-w-0 flex-1 justify-start gap-2 rounded-md px-1 py-1 pr-10 text-left text-sm"><Archive size={14} className="shrink-0 text-muted-foreground" /><span className="min-w-0 flex-1"><span className="block truncate">{item.title || 'Untitled session'}</span><span className="flex min-w-0 items-center gap-1 truncate text-[10px] text-muted-foreground">{[item.project || item.project_id, ...(item.tags || [])].filter(Boolean).join(' · ')}{channel && <span className="rounded border px-1 uppercase tracking-wide">{channel}</span>}</span></span>{item.pinned && <Pin size={12} className="shrink-0 text-primary" />}</Button>
          <div className="absolute right-1 top-1/2 flex -translate-y-1/2 rounded-md bg-card/95 opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100"><DropdownMenu label={`Actions for ${item.title || 'session'}`} items={[{ label: 'Rename conversation', icon: Pencil, onSelect: () => { setRenameTarget(item); setRenameValue(item.title || '') } }, { label: 'Duplicate conversation', icon: Copy, onSelect: () => { if (onDuplicate) void onDuplicate(item.session_id) } }, { label: 'Export Markdown', icon: Download, onSelect: () => { window.location.assign(sessionExportUrl(item.session_id)) } }, { label: item.pinned ? 'Unpin conversation' : 'Pin conversation', icon: Pin, onSelect: () => onPin(item.session_id, !item.pinned) }, { label: item.archived ? 'Unarchive conversation' : 'Archive conversation', icon: item.archived ? Archive : ArchiveX, onSelect: () => onArchive(item.session_id, !item.archived) }, { label: 'Delete conversation', icon: Trash2, onSelect: () => setDeleteTarget(item), destructive: true }]} /></div>
        </div> })}</div>)}
        {!loading && !error && sessions.length > 0 && groups.length === 0 && <p className="px-3 py-2 text-xs text-muted-foreground">No sessions match these filters.</p>}
      </div>
    </aside>
    <Dialog open={Boolean(renameTarget)} title="Rename session" onClose={() => setRenameTarget(null)}><form className="grid gap-3" onSubmit={event => { event.preventDefault(); if (renameTarget && renameValue.trim()) { void onRename(renameTarget.session_id, renameValue.trim()); setRenameTarget(null) } }}><Input autoFocus value={renameValue} onChange={event => setRenameValue(event.target.value)} placeholder="Session name" aria-label="Session name" /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setRenameTarget(null)}>Cancel</Button><Button type="submit" disabled={!renameValue.trim()}>Rename</Button></div></form></Dialog>
    <Dialog open={Boolean(deleteTarget)} title="Delete session?" onClose={() => setDeleteTarget(null)}><p className="text-sm text-muted-foreground">This removes the saved session and its transcript.</p><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDeleteTarget(null)}>Cancel</Button><Button type="button" onClick={() => { if (deleteTarget) void onDelete(deleteTarget.session_id); setDeleteTarget(null) }}>Delete session</Button></div></Dialog>
  </>
}
