import { useEffect, useState } from 'react'
import { Check, CirclePlus, Trash2 } from 'lucide-react'
import { Button } from '../ui/button'
import { createControl, deleteControl, getControl, updateControl, type ControlItem } from '../../lib/control-client'

const collections = ['tasks', 'todos', 'goals', 'spaces'] as const
type Props = { view: string }
export function ControlCenter({ view }: Props) {
  if (view === 'skills' || view === 'memory') return <DiscoveryView view={view} />
  const collection = collections.includes(view as typeof collections[number]) ? view : 'tasks'; const [items, setItems] = useState<ControlItem[]>([]); const [title, setTitle] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const refresh = async () => { setLoading(true); try { setItems(await getControl(collection)); setError('') } catch (err) { setError(err instanceof Error ? err.message : 'Control center unavailable') } finally { setLoading(false) } }
  useEffect(() => { void refresh() }, [collection])
  const add = async () => { if (!title.trim()) return; try { await createControl(collection, title.trim()); setTitle(''); await refresh() } catch (err) { setError(err instanceof Error ? err.message : 'Could not create item') } }
  return <section className="mx-auto w-full max-w-3xl p-5 sm:p-8"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-[11px] uppercase tracking-[0.18em] text-primary">Control center</p><h1 className="mt-2 text-2xl font-semibold capitalize">{collection}</h1><p className="mt-1 text-sm text-muted-foreground">Server-persisted {collection} with explicit status and empty states.</p></div></div><form className="mb-5 flex gap-2" onSubmit={e => { e.preventDefault(); void add() }}><label className="sr-only" htmlFor="control-title">New item</label><input id="control-title" value={title} onChange={e => setTitle(e.target.value)} placeholder={`Add a ${collection.slice(0, -1)}`} className="h-10 min-w-0 flex-1 rounded-lg border bg-card px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /><Button type="submit"><CirclePlus size={16} />Add</Button></form>{error && <p role="alert" className="mb-4 rounded border border-destructive/40 p-3 text-sm text-red-300">{error}</p>}{loading ? <p role="status" className="text-sm text-muted-foreground">Loading {collection}...</p> : items.length === 0 ? <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Nothing here yet. Add the first item above.</div> : <div className="space-y-2">{items.map(item => <article key={item.id} className="flex min-h-14 items-center gap-3 rounded-lg border bg-card px-3"><button type="button" className="grid size-9 shrink-0 place-items-center rounded hover:bg-accent" aria-label={`Mark ${item.title} done`} onClick={() => void updateControl(collection, item.id, item.status === 'done' ? 'open' : 'done').then(refresh)}><Check size={16} className={item.status === 'done' ? 'text-primary' : 'text-muted-foreground'} /></button><div className="min-w-0 flex-1"><p className={item.status === 'done' ? 'truncate text-sm text-muted-foreground line-through' : 'truncate text-sm'}>{item.title}</p><p className="text-[11px] text-muted-foreground">{item.status}</p></div><Button variant="ghost" size="icon" aria-label={`Delete ${item.title}`} onClick={() => void deleteControl(collection, item.id).then(refresh)}><Trash2 size={14} /></Button></article>)}</div>}</section>
}

function DiscoveryView({ view }: { view: 'skills' | 'memory' }) {
  const [items, setItems] = useState<{ name: string; path: string }[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { void fetch(`/api/${view}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Discovery unavailable'); setItems(data[view === 'skills' ? 'skills' : 'notes'] || []) }).catch(err => setError(err instanceof Error ? err.message : 'Discovery unavailable')).finally(() => setLoading(false)) }, [view])
  return <section className="mx-auto w-full max-w-3xl p-5 sm:p-8"><p className="text-[11px] uppercase tracking-[0.18em] text-primary">Control center</p><h1 className="mt-2 text-2xl font-semibold capitalize">{view}</h1><p className="mt-1 text-sm text-muted-foreground">Server-owned discovery surface. Empty means no local entries were found.</p>{error && <p role="alert" className="mt-5 rounded border border-destructive/40 p-3 text-sm text-red-300">{error}</p>}{loading ? <p role="status" className="mt-5 text-sm text-muted-foreground">Loading {view}...</p> : items.length === 0 ? <div className="mt-5 rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No {view} entries found.</div> : <div className="mt-5 space-y-2">{items.map(item => <div key={item.path} className="rounded-lg border bg-card px-4 py-3 text-sm">{item.name}</div>)}</div>}</section>
}
