import { Activity, BarChart3, Coins, RefreshCw, Server, Waypoints } from 'lucide-react'
import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { Button } from '../ui/button'
import { getInsights, type InsightsResponse } from '../../lib/insights-client'

const formatNumber = (value: number) => new Intl.NumberFormat().format(value)
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : 'No recorded activity'

export function InsightsView() {
  const [data, setData] = useState<InsightsResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const refresh = useCallback(async (signal?: AbortSignal) => {
    setLoading(true)
    try { setData(await getInsights(signal)); setError('') }
    catch (err) { if (err instanceof Error && err.name === 'AbortError') return; setError(err instanceof Error ? err.message : 'Insights are unavailable.') }
    finally { if (!signal?.aborted) setLoading(false) }
  }, [])
  useEffect(() => { const controller = new AbortController(); void refresh(controller.signal); return () => controller.abort() }, [refresh])

  return <section className="mx-auto w-full max-w-4xl p-5 sm:p-8" aria-labelledby="insights-title">
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-primary">Operational view</p><h1 id="insights-title" className="mt-1 text-xl font-semibold">Insights</h1><p className="mt-0.5 max-w-xl text-xs text-muted-foreground">Recorded usage and provider history from the server-owned Hermes session state.</p></div><Button type="button" variant="outline" size="sm" className="h-8 rounded-xl px-3 text-xs" onClick={() => void refresh()} disabled={loading}><RefreshCw size={13} aria-hidden="true" />{loading ? 'Reading state' : 'Refresh'}</Button></div>
    {error && <div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-destructive/40 bg-destructive/10 p-3.5" role="alert"><p className="text-xs text-red-300">{error}</p><Button type="button" variant="outline" size="sm" className="h-7 rounded-lg text-xs" onClick={() => void refresh()}>Try again</Button></div>}
    {loading && !data ? <p role="status" className="text-xs text-muted-foreground">Reading recorded Hermes state...</p> : data && <>
      <div className="mb-4 grid gap-2.5 sm:grid-cols-2 lg:grid-cols-4"><InsightMetric icon={<Activity size={15} />} label="Sessions" value={formatNumber(data.summary.sessions)} detail={`${formatNumber(data.summary.messages)} recorded messages`} /><InsightMetric icon={<Waypoints size={15} />} label="Conversation split" value={`${formatNumber(data.summary.user_messages)} / ${formatNumber(data.summary.assistant_messages)}`} detail="User / Hermes messages" /><InsightMetric icon={<BarChart3 size={15} />} label="Tokens" value={data.usage.available ? formatNumber(data.usage.total_tokens) : 'Not recorded'} detail={data.usage.available ? `${formatNumber(data.usage.input_tokens)} in · ${formatNumber(data.usage.output_tokens)} out` : 'No usage events'} /><InsightMetric icon={<Server size={15} />} label="State sync" value={data.synchronization.status} detail={`${formatNumber(data.synchronization.sessions_read)}/${formatNumber(data.synchronization.sessions_scanned)} sessions`} /></div>
      <div className="grid gap-3 lg:grid-cols-[1.25fr_0.75fr]"><section className="rounded-xl border border-border/70 bg-card/70 p-4 shadow-sm" aria-labelledby="provider-history-title"><div className="flex items-start justify-between gap-3"><div><h2 id="provider-history-title" className="text-sm font-semibold text-foreground">Provider history</h2><p className="mt-0.5 text-xs text-muted-foreground">Only provider and model values persisted with a session are shown.</p></div><Server size={15} className="text-muted-foreground" aria-hidden="true" /></div>{data.provider_history.length === 0 ? <p className="mt-4 rounded-lg border border-dashed border-border/70 p-4 text-xs text-muted-foreground">No provider history is recorded yet.</p> : <div className="mt-3 space-y-1.5">{data.provider_history.map(item => <article key={`${item.provider}-${item.model || 'default'}`} className="flex flex-wrap items-center gap-2.5 rounded-lg border border-border/60 bg-muted/20 px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{item.provider}</p><p className="truncate text-[10px] text-muted-foreground">{item.model || 'Model not recorded'} · {formatNumber(item.sessions)} {item.sessions === 1 ? 'session' : 'sessions'}</p></div><p className="text-right text-[11px] text-muted-foreground">{formatNumber(item.messages)} msgs{item.usage.available && <><br />{formatNumber(item.usage.total_tokens)} tokens</>}</p></article>)}</div>}</section><section className="rounded-xl border border-border/70 bg-card/70 p-4 shadow-sm" aria-labelledby="state-summary-title"><div className="flex items-start justify-between gap-3"><div><h2 id="state-summary-title" className="text-sm font-semibold text-foreground">State summary</h2><p className="mt-0.5 text-xs text-muted-foreground">Read time and billing availability.</p></div><Coins size={15} className="text-muted-foreground" aria-hidden="true" /></div><dl className="mt-3 space-y-3 text-xs"><div><dt className="text-[10px] text-muted-foreground">Last recorded activity</dt><dd className="mt-0.5 text-xs font-medium text-foreground">{formatDate(data.synchronization.last_activity_at)}</dd></div><div><dt className="text-[10px] text-muted-foreground">Cost</dt><dd className="mt-0.5 text-xs font-medium text-foreground">{data.cost.available ? 'Recorded' : 'Not available'}</dd>{!data.cost.available && <p className="mt-0.5 text-[10px] text-muted-foreground">{data.cost.reason}</p>}</div><div><dt className="text-[10px] text-muted-foreground">Source</dt><dd className="mt-0.5 break-words font-mono text-[10px] text-muted-foreground">{data.source}</dd></div></dl></section></div>
    </>}
  </section>
}

function InsightMetric({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <article className="rounded-xl border border-border/70 bg-card/70 p-3.5 shadow-sm"><div className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">{icon}<span>{label}</span></div><p className="mt-2.5 truncate text-lg font-semibold text-foreground" title={value}>{value}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{detail}</p></article> }

