import { Download, File, Folder, FolderPlus, Pencil, Plus, RefreshCw, Trash2, Upload, X } from 'lucide-react'
import { useRef, useState, type CSSProperties } from 'react'
import { Button } from '../ui/button'
import { Textarea } from '../ui/textarea'
import { Input } from '../ui/input'
import { Dialog } from '../ui/dialog'
import { SafeMarkdown } from '../../lib/markdown'
import { breadcrumbs, type WorkspacePreview } from '../../lib/workspace-contract'
import { workspaceDownloadUrl } from '../../lib/api-client'

type Props = ReturnType<typeof import('../../hooks/use-workspace').useWorkspace> & { width: number; onWidthChange: (width: number) => void }
export function WorkspacePanel({ open, setOpen, path, entries, preview, setPreview, git, loading, error, refresh, select, save, create, rename, remove, upload, width, onWidthChange }: Props) {
  const input = useRef<HTMLInputElement>(null); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(''); const [nameDialog, setNameDialog] = useState<{ title: string; action: (value: string) => void } | null>(null); const [nameValue, setNameValue] = useState(''); const [deleteOpen, setDeleteOpen] = useState(false)
  if (!open) return null
  const act = (label: string, fn: (value: string) => void) => { setNameValue(''); setNameDialog({ title: label, action: fn }) }
  const show = (item: WorkspacePreview) => item.binary ? <div className="flex flex-col gap-3 text-xs text-muted-foreground"><span>Binary file · {item.mime || 'unknown type'}</span><a className="text-primary underline" href={workspaceDownloadUrl(item.path)} download>Download file</a></div> : item.mime?.startsWith('image/') ? <img className="max-h-80 max-w-full rounded border object-contain" src={workspaceDownloadUrl(item.path)} alt={item.name} /> : item.name.endsWith('.md') ? <div className="message-markdown text-sm"><SafeMarkdown>{item.content || ''}</SafeMarkdown></div> : editing ? <Textarea autoFocus className="min-h-72 font-mono text-xs" value={draft} onChange={e => setDraft(e.target.value)} /> : <pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap break-words rounded border bg-background p-3 font-mono text-xs">{item.content}</pre>
  return <aside className="workspace-panel relative flex h-full shrink-0 flex-col border-l bg-card" style={{ '--workspace-width': `${width}px` } as CSSProperties} aria-label="Workspace">
    <div className="workspace-resizer" role="separator" aria-label="Resize workspace" tabIndex={0} aria-valuenow={width} onKeyDown={e => { if (e.key === 'ArrowLeft') onWidthChange(width - 20); if (e.key === 'ArrowRight') onWidthChange(width + 20) }} onPointerDown={e => { const start = e.clientX; const initial = width; const move = (event: PointerEvent) => onWidthChange(initial - (event.clientX - start)); const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up) }} />
    <header className="flex min-h-14 items-center gap-2 border-b px-3"><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">Workspace</h2><p className="truncate text-[11px] text-muted-foreground">{git?.branch || 'Local files'}</p></div><Button variant="ghost" size="icon" onClick={() => void refresh()} aria-label="Refresh workspace"><RefreshCw size={15} /></Button><Button variant="ghost" size="icon" onClick={() => setOpen(false)} aria-label="Close workspace"><X size={17} /></Button></header>
    <div className="flex gap-1 overflow-x-auto border-b px-3 py-2">{breadcrumbs(path).map(item => <Button variant="ghost" size="sm" className="h-7 shrink-0 px-2 text-xs text-muted-foreground" key={item.path} onClick={() => void refresh(item.path)}>{item.label}</Button>)}</div>
    <div className="flex items-center gap-1 border-b px-2 py-1"><Button variant="ghost" size="sm" onClick={() => act('New file name', n => void create(`${path === '.' ? '' : path + '/'}${n}`, 'file'))}><Plus size={14} />File</Button><Button variant="ghost" size="sm" onClick={() => act('New folder name', n => void create(`${path === '.' ? '' : path + '/'}${n}`, 'directory'))}><FolderPlus size={14} />Folder</Button><Button variant="ghost" size="sm" onClick={() => input.current?.click()}><Upload size={14} />Upload</Button><input ref={input} hidden type="file" onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); e.currentTarget.value = '' }} /></div>
    {error && <p className="border-b border-destructive/40 p-3 text-xs text-red-300">{error}</p>}
    <div className="thin-scrollbar min-h-0 flex-1 overflow-y-auto p-2">{loading ? <p className="p-2 text-xs text-muted-foreground">Loading workspace...</p> : entries.length === 0 ? <p className="p-2 text-xs text-muted-foreground">This folder is empty.</p> : entries.map(entry => <Button variant="ghost" size="sm" key={entry.path} className="flex min-h-10 w-full justify-start gap-2 rounded px-2 text-left text-xs" onClick={() => void select(entry)}>{entry.type === 'directory' ? <Folder size={15} className="text-primary" /> : <File size={15} className="text-muted-foreground" />}<span className="truncate">{entry.name}</span></Button>)}</div>
    {preview && <section className="max-h-[52%] overflow-auto border-t p-3"><div className="mb-2 flex items-center gap-1"><strong className="min-w-0 flex-1 truncate text-xs">{preview.name}</strong>{preview.editable && !preview.binary && <Button variant="ghost" size="icon" onClick={() => { setDraft(preview.content || ''); setEditing(!editing) }} aria-label="Edit file"><Pencil size={14} /></Button>}<Button variant="ghost" size="icon" onClick={() => act('New name', n => void rename(preview.path, n))} aria-label="Rename file"><Pencil size={14} /></Button><a className="grid size-9 place-items-center rounded text-muted-foreground hover:bg-accent" href={workspaceDownloadUrl(preview.path)} download aria-label="Download file"><Download size={15} /></a><Button variant="ghost" size="icon" onClick={() => setDeleteOpen(true)} aria-label="Delete file"><Trash2 size={14} /></Button></div>{show(preview)}{editing && <div className="mt-2 flex gap-2"><Button size="sm" onClick={() => { void save(draft); setEditing(false) }}>Save</Button><Button size="sm" variant="outline" onClick={() => setEditing(false)}>Cancel</Button></div>}</section>}
    <Dialog open={Boolean(nameDialog)} title={nameDialog?.title || ''} onClose={() => setNameDialog(null)}><form className="grid gap-3" onSubmit={event => { event.preventDefault(); if (nameDialog && nameValue.trim()) { nameDialog.action(nameValue.trim()); setNameDialog(null) } }}><Input autoFocus value={nameValue} onChange={event => setNameValue(event.target.value)} placeholder="Enter a name" aria-label="Name" /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setNameDialog(null)}>Cancel</Button><Button type="submit" disabled={!nameValue.trim()}>Continue</Button></div></form></Dialog><Dialog open={deleteOpen} title="Delete item?" onClose={() => setDeleteOpen(false)}><p className="text-sm text-muted-foreground">This removes the selected workspace item.</p><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDeleteOpen(false)}>Cancel</Button><Button type="button" onClick={() => { if (preview) void remove(preview.path); setDeleteOpen(false) }}>Delete item</Button></div></Dialog>
  </aside>
}
