import { useEffect, useState } from 'react'
import { LogIn, LogOut, ShieldCheck } from 'lucide-react'
import { Button } from '../ui/button'
import { Input } from '../ui/input'
import { Select } from '../ui/select'

type Profile = { id: string; name: string; model: string; provider?: string; health: string }
export function IdentityControls() {
  const [configured, setConfigured] = useState(false); const [authenticated, setAuthenticated] = useState(false); const [password, setPassword] = useState(''); const [profiles, setProfiles] = useState<Profile[]>([]); const [active, setActive] = useState('default'); const [message, setMessage] = useState('')
  const refresh = async () => { const [onboarding, me, profileData] = await Promise.all([fetch('/api/onboarding').then(r => r.json()), fetch('/api/auth/me').then(r => r.json()), fetch('/api/profiles').then(r => r.json())]); setConfigured(onboarding.configured); setAuthenticated(me.authenticated); setProfiles(profileData.profiles || []); setActive(profileData.active || 'default') }
  useEffect(() => { void refresh().catch(() => setMessage('Identity service unavailable')) }, [])
  const submit = async () => { const endpoint = configured ? '/api/auth/login' : '/api/onboarding/password'; const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); const data = await response.json(); if (!response.ok) { setMessage(data.message || 'Authentication failed'); return }; setPassword(''); setMessage(''); await refresh() }
  const switchProfile = async (id: string) => { const response = await fetch('/api/profiles/active', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); if (response.ok) setActive(id) }
  return <div className="flex min-w-0 items-center gap-2"><Select className="hidden h-8 max-w-32 px-2 text-xs sm:block" aria-label="Active profile" value={active} onChange={e => void switchProfile(e.target.value)}>{profiles.map(profile => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</Select>{configured && authenticated ? <Button variant="ghost" size="icon" aria-label="Sign out" onClick={() => { void fetch('/api/auth/logout', { method: 'POST' }).then(() => refresh()) }}><LogOut size={15} /></Button> : <form className="flex min-w-0 items-center gap-1" onSubmit={e => { e.preventDefault(); void submit() }}><label className="sr-only" htmlFor="identity-password">{configured ? 'Password' : 'Create password'}</label><Input id="identity-password" type="password" minLength={12} placeholder={configured ? 'Password' : 'Create password'} value={password} onChange={e => setPassword(e.target.value)} className="h-8 w-24 px-2 text-xs sm:w-28" />{configured ? <Button type="submit" variant="ghost" size="icon" aria-label="Sign in"><LogIn size={15} /></Button> : <Button type="submit" variant="ghost" size="icon" aria-label="Set up password"><ShieldCheck size={15} /></Button>}</form>}{message && <span className="sr-only" role="status">{message}</span>}</div>
}
