export const statuses = ['triage', 'todo', 'scheduled', 'ready', 'running', 'blocked', 'review', 'done', 'archived'] as const
export type TaskStatus = typeof statuses[number]

export type KanbanTask = {
  id: string; title: string; body?: string; status: TaskStatus; assignee?: string; priority: number
  tenant?: string; workspace?: string; skills: string[]; parents: string[]; children: string[]
  commentCount: number; createdAt?: string; updatedAt?: string
}
export type KanbanBoard = { slug: string; name?: string; taskCount?: number; archived?: boolean }
export type KanbanPayload = { tasks: KanbanTask[]; boards: KanbanBoard[]; tenants: string[]; assignees: string[]; stats: Record<string, number> }
export type KanbanCapabilities = { transport: string; available: boolean; features: Record<string, boolean>; statuses: string[]; dashboard?: { configured: boolean; available: boolean } }
export type KanbanSpace = { id: string; title: string; path: string; status?: string; active?: boolean }

const text = (value: unknown) => typeof value === 'string' ? value : value == null ? '' : String(value)
const list = (value: unknown) => Array.isArray(value) ? value : []
const item = (value: unknown): Record<string, unknown> => value && typeof value === 'object' ? value as Record<string, unknown> : {}
const number = (value: unknown, fallback = 0) => typeof value === 'number' ? value : Number(value) || fallback
export const normalizeTask = (raw: unknown): KanbanTask => { const v = item(raw); const status = text(v.status) as TaskStatus; return { id: text(v.id), title: text(v.title), body: text(v.body) || undefined, status: statuses.includes(status) ? status : 'todo', assignee: text(v.assignee) || undefined, priority: number(v.priority), tenant: text(v.tenant) || undefined, workspace: text(v.workspace) || undefined, skills: list(v.skills).map(text), parents: list(v.parents).map(text), children: list(v.children).map(text), commentCount: number(v.comment_count ?? v.commentCount), createdAt: text(v.created_at ?? v.createdAt) || undefined, updatedAt: text(v.updated_at ?? v.updatedAt) || undefined } }

export async function read<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const raw = await response.text(); let data: (T & { message?: string }) | null = null; try { data = raw.trim() ? JSON.parse(raw) as T & { message?: string } : null } catch { const detail = raw.trim().replace(/\s+/g, ' ').slice(0, 160); throw new Error(response.ok ? `Invalid JSON response from Kanban server${detail ? `: ${detail}` : '.'}` : `Kanban request failed (${response.status})${detail ? `: ${detail}` : ''}`) } if (!response.ok) throw new Error(data?.message || `Kanban request failed (${response.status})`); if (!data) throw new Error('Kanban server returned an empty response.'); return data }
export async function getCapabilities() { return read<KanbanCapabilities>('/api/kanban/capabilities') }
export async function getSpaces() { const data = await read<{ active?: string; spaces?: Array<{ id: string; title: string; status?: string; metadata?: { path?: string; active?: string } }> }>('/api/spaces'); return (data.spaces || []).map(space => ({ id: space.id, title: space.title, path: space.metadata?.path || '', status: space.status, active: space.id === data.active || space.metadata?.active === 'true' })) }
export async function getBoards() { const data = await read<unknown>('/api/kanban/boards'); const raw = Array.isArray(data) ? data : item(data).boards; return list(raw).map(v => { const b = item(v); return { slug: text(b.slug || b.id), name: text(b.name) || undefined, taskCount: number(b.task_count ?? b.taskCount), archived: Boolean(b.archived) } }) }
export async function getBoard(board: string, includeArchived = false): Promise<KanbanPayload> { const data = await read<unknown>(`/api/kanban/board?board=${encodeURIComponent(board)}&include_archived=${includeArchived}`); const root = item(data); const rawTasks: unknown[] = (list(root.tasks).length ? list(root.tasks) : list(data)) as unknown[]; const tasks: KanbanTask[] = rawTasks.map(normalizeTask).filter((value: KanbanTask) => Boolean(value.id)); const stats = tasks.reduce<Record<string, number>>((result: Record<string, number>, value: KanbanTask) => { result[value.status] = (result[value.status] || 0) + 1; return result }, {}); return { tasks, boards: list(root.boards).map(v => { const b = item(v); return { slug: text(b.slug || b.id), name: text(b.name) || undefined, taskCount: number(b.task_count ?? b.taskCount), archived: Boolean(b.archived) } }), tenants: list(root.tenants).map(text).filter(Boolean), assignees: list(root.assignees).map(text).filter(Boolean), stats } }
export async function getTask(id: string) { const data = await read<unknown>(`/api/kanban/tasks/${encodeURIComponent(id)}`); const root = item(data); return { ...normalizeTask(data), comments: list(root.comments), events: list(root.events), runs: list(root.runs), result: text(root.result) || undefined } }
export async function createTask(board: string, payload: Record<string, unknown>) { return read<unknown>(`/api/kanban/tasks?board=${encodeURIComponent(board)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }) }
export async function taskAction(board: string, id: string, action: string) { return read<unknown>(`/api/kanban/tasks/${encodeURIComponent(id)}/actions/${action}?board=${encodeURIComponent(board)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }) }
